### ISSUE TITLE
建议前期可以对包名等声明文件进行命名规范修改

### ISSUE THREAD

**Issue by Jzow** [Charity-Software-Organization/philippines-hs-project#1]
可以一起找个时间协商命名规范

@1934312221

**Comment by 1934312221** [comment]
收到


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Charity-Software-Organization/philippines-hs-project"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月1日(星期一) 下午5:27
收件人:&nbsp;"Charity-Software-Organization/philippines-hs-project"<philippines-hs-project@noreply.github.com&gt;;
抄送:&nbsp;"大鑫"<1934312221@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;[Charity-Software-Organization/philippines-hs-project] 建议前期可以对包名等声明文件进行命名规范修改 (#1)





 
可以一起找个时间协商命名规范
 
@1934312221
